rename:
  caracteristiques-2017.csv: caracteristiques_2017.csv
  caracteristiques-2018.csv: caracteristiques_2018.csv
  caracteristiques-2019.csv: caracteristiques_2019.csv
  caracteristiques-2020.csv: caracteristiques_2020.csv
  carcteristiques-2021.csv: caracteristiques_2021.csv
  carcteristiques-2022.csv: caracteristiques_2022.csv
  lieux-2017.csv: lieux_2017.csv
  lieux-2018.csv: lieux_2018.csv
  lieux-2019.csv: lieux_2019.csv
  lieux-2020.csv: lieux_2020.csv
  lieux-2021.csv: lieux_2021.csv
  lieux-2022.csv: lieux_2022.csv
  usagers-2017.csv: usagers_2017.csv
  usagers-2018.csv: usagers_2018.csv
  usagers-2019.csv: usagers_2019.csv
  usagers-2020.csv: usagers_2020.csv
  usagers-2021.csv: usagers_2021.csv
  usagers-2022.csv: usagers_2022.csv
  vehicules-2017.csv: vehicules_2017.csv
  vehicules-2018.csv: vehicules_2018.csv
  vehicules-2019.csv: vehicules_2019.csv
  vehicules-2020.csv: vehicules_2020.csv
  vehicules-2021.csv: vehicules_2021.csv
  vehicules-2022.csv: vehicules_2022.csv

sep:
  caracteristiques_2009.csv: '\t'
  caracteristiques_2019.csv: ';'
  caracteristiques_2020.csv: ';'
  caracteristiques_2021.csv: ';'
  caracteristiques_2022.csv: ';'
  lieux_2019.csv: ';'
  lieux_2020.csv: ';'
  lieux_2021.csv: ';'
  lieux_2022.csv: ';'
  usagers_2019.csv: ';'
  usagers_2020.csv: ';'
  usagers_2021.csv: ';'
  usagers_2022.csv: ';'
  vehicules_2019.csv: ';'
  vehicules_2020.csv: ';'
  vehicules_2021.csv: ';'
  vehicules_2022.csv: ';'
